---
- name: Copy Chrome web browser extension.
  copy:
    src: "{{ jitsi_meet_desktop_sharing_chrome_extension_filename }}"
    dest: "/usr/share/jitsi-meet/{{ jitsi_meet_desktop_sharing_chrome_extension_filename | basename }}"
  notify: restart nginx
  when: jitsi_meet_desktop_sharing_chrome_extension_filename is defined and
        jitsi_meet_desktop_sharing_chrome_extension_filename != ''
