---
- name: Install base apt packages.
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ jitsi_meet_base_packages }}"

- name: Add signing key for Jitsi repository
  apt_key:
    keyserver: keys.gnupg.net
    id: C697D823EB0AB654

# Prior versions of the role were writing to this file, let's
# clean it up and use a generalized filename for configuring the apt repo,
# regardless of whether stable or unstable is used.
- name: Remove deprecated repo filename.
  file:
    path: /etc/apt/sources.list.d/download_jitsi_org_nightly_deb.list
    state: absent

- name: Install Jitsi apt repo.
  apt_repository:
    repo: "{{ jitsi_meet_apt_repo }}"
    state: present
    # Ansible will automatically add the ".list" suffix.
    filename: /etc/apt/sources.list.d/jitsi_meet

- name: Install Jitsi Meet
  apt:
    name: jitsi-meet
    state: present
    update_cache: yes

- name: Set debconf options for jitsi-meet.
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ jitsi_meet_debconf_settings }}"
  notify:
    - restart jitsi-videobridge
    - restart jicofo
    - restart prosody
