---

- name: Install jigasi
  apt:
    name: jigasi
    state: present

- name: Set debconf options for jigasi
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - name: jigasi
      question: jigasi/sip-account
      value: "{{ jitsi_meet_jigasi_account }}"
      vtype: string
    - name: jigasi
      question: jigasi/sip-password
      value: "{{ jitsi_meet_jigasi_password }}"
      vtype: string

- name: Add videobridge sip-communicator config
  template:
    src: "{{ jitsi_meet_jigasi_videobridge_sip_template }}"
    dest: /etc/jitsi/videobridge/sip-communicator.properties
    mode: 0644
  notify: restart jitsi-videobridge
