---

- name: set NPROC
  replace:
    path: /etc/systemd/system.conf
    regexp: '#DefaultLimitNPROC=$'
    replace: 'DefaultLimitNPROC=65000'
  notify: reload systemctl

- name: set TasksMax
  replace:
    path: /etc/systemd/system.conf
    regexp: '#DefaultTasksMax=$'
    replace: 'DefaultTasksMax=65000'
  notify: reload systemctl

- name: set NOFILE
  replace:
    path: /etc/systemd/system.conf
    regexp: '#DefaultLimitNOFILE=$'
    replace: 'DefaultLimitNOFILE=65000'
  notify: reload systemctl