---

- name: Copy Jitsi Videobridge config file.
  template:
    src: videobridge_config.j2
    dest: /etc/jitsi/videobridge/config
    owner: root
    group: root
    mode: "0644"
  notify: restart jitsi-videobridge

- name: Set jitsi-videobridge log level.
  lineinfile:
    dest: /etc/jitsi/videobridge/logging.properties
    regexp: '^\.level'
    line: ".level={{ jitsi_meet_videobridge_loglevel }}"
    state: present
  notify: restart jitsi-videobridge
